### ISSUE TITLE
Change Marker Popup to `doubleClick` event

### ISSUE THREAD

**Issue by hawgview** [hawgview/HawgView#10]
Requested by Switch

## Description
Change the marker popup to display on double click

## Details
Porkins' idea is to have a user selectable setting to change this behavior for single or double click.
This should be saved in the user's cookies/cache to prevent the user from needing to change this setting continuously

**Comment by chris-m92** [comment]
## Updates
-[X] Styles updated to include marker popup behavior
-[X] Styles updated to save to `localstorage` on machine
-[X] App updated to load `localstorage` preferences to application on load
-[ ] Need to move `MarkerPopup` to separate popup component (details below)

### Details
Marker Popup is currently bound to each marker as a separate instance. Instead, to make this work, have `MarkerPopup` be a separate and isolate instance of a popup. Move `MarkerPopup` properties to a slice in state. The click or double click will then dispatch the properties to state. The popup will then be shown if the properties are valid. Closing the popup will then also reset the properties value to `null`. This also has the benefit of finer control on popups showing up when interacting with the map.

- [ ] Confirm with Switch/Tarzan if they also want `MapPopup` to be tied to the same `PopupBehaviors` or to maintain single click/coordinate search to open map popup

**Comment by chris-m92** [comment]
## Released in v3.17.0
* Close #11 
- [X] Styles include `popup behavior`
- [X] Users can change `popup behavior` in Styles menu
- [X] Markers respond by only opening popup whenever the marker is set to the focused object, which is tied to the single or double click events

### Limitations
Shapes do not respond to the same events as markers. There is no behavior change in `v3.17.0`. In testing, shapes would not respond to double clicks and had a low success rate in responding to single clicks. Thus, their behavior remains native to React Leaflet
