### ISSUE TITLE
Move user preferences to cookies/cache

### ISSUE THREAD

**Issue by hawgview** [hawgview/HawgView#11]
## Description
Move all user preferences (to include styles, and site settings) to cookies.

**Comment by chris-m92** [comment]
## Updates
- [X] In conjunction with #10, store styles object in `localStorage` whenever updated
- [X] Load preferences from `localStorage` on application load
- [X] If no preferences are found in `localStorage`, initialize `localStorage` prefs with default values.

**Comment by chris-m92** [comment]
## Released in v3.17.0
- Close #10 
- [X] Styles are stored in browser storage whenever updated
- [X] Styles are loaded from browser storage on application load
- [X] Styles are initialized whenever none are found
