### ISSUE TITLE
Filter marker list

### ISSUE THREAD

**Issue by hawgview** [hawgview/HawgView#12]
Requested by Switch

## Description
Allow the users to filter marker list categories further based on tags

## Details
Porkins' idea is to add tags to markers which could be user editable, but default to the following attributes
* Map Layer
* Mil Symbol entity type
* Mil Symbol modifiers
* Mil Symbol Echelon
* Higher Formation
* Etc...

**Comment by chris-m92** [comment]
## Released in v3.20.4
- [X] Users can now filter Military Symbol MIL-STD-2525D markers by their attributes.
- [X] Filters extend to both normal scenario marker list as well as Search results
- [X] Filters are applied to scenarios that are then saved as CSV and Hawg View scenarios
- [X] Filters are applied to printouts
