### ISSUE TITLE
Container NAI search

### ISSUE THREAD

**Issue by hawgview** [hawgview/HawgView#13]
Requested by Tarzan

## Description
Allow users such as White Cell to create a bounding box defined by coordinates or drawn on the map and return a list of units that are within the bounding box.

**Comment by chris-m92** [comment]
## Released in v3.18.1 (29 Apr 2022)
- [X] Users can designate an NAI container using the new `Container Search Tool`
- [X] Once designated, the NAI container returns all markers that are within the bounds of the search area
- [X] Users will then be able to print or save the results as a new Hawg View scenario or as a `.csv` file
