### ISSUE TITLE
Merge Scenarios

### ISSUE THREAD

**Issue by hawgview** [hawgview/HawgView#3]
Requested by Alamo and Tarzan

## Description
Add scenario merging options back to Hawg View

## Expected Behavior
When loading a scenario, give the option to merge into the current scenario or overwrite the current scenario

## Current Behavior
Loading a scenario only overwrites the current scenario with what has been loaded

## Steps to reproduce
Load a scenario (`ScenarioA`) and then load a second scenario (`ScenarioB`). When loaded, `ScenarioA` is overwritten by `ScenarioB`.

**Comment by chris-m92** [comment]
Resolved in Update `3.16.1`

Users can now select multiple files when loading a scenario file.
Users can also choose between two different behaviors: Overwrite and Merge
- In either case, all selected files will be merged into one "Loaded scenario"
- If the user chooses overwrite, the "Loaded scenario" will overwrite the current scenario
- If the user chooses merge, the "Loaded scenario" will be merged with the current scenario

Markers and shapes are deconflicted according to the following properties
- ID number
- Title
- Lat/Lng position
This means that if you load the same scenario twice, any markers with the same ID, title, and position will be OMITTED from the merge.
